### ISSUE TITLE
Incorporate linting to the CI workflow

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/rBAPS#23]
See example [here](https://github.com/r-lib/actions/tree/master/examples#lint-workflow). The basic idea, though, is to add this job to `r.yml`:

```yml
- name: Linting package
  run: lintr::lint_package()
  shell: Rscript {0}
```
